name: Generate "lowercase" policy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - checks/**

permissions: {}

env:
  FRAMEWORK: "SSDF"

jobs:
  generate-policy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: '1.24'
          cache: false
          check-latest: true

      - name: Setup ORAS CLI
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6 # v1.2.4

      - name: Setup c2pcli
        uses: jpower432/c2p-actions/actions/setup-c2pcli@0bc42f492f3a6854fe0afc99c50100db8f5e17c6 # main

      - name: Install C2P plugins
        uses: ./.github/actions/install-conforma-plugin

      - name: Setup dirs
        run: mkdir -p policies/opa policy-results/opa

      - name: Add GitHub ORG to config
        env:
          ORG: ${{ github.event.repository.owner.login }}
        run: sed -i "s/{{ ORG }}/$ORG/g" configs/c2p-config.yaml

      - name: Generate policy bundle
        run: c2pcli oscal2policy -c configs/c2p-config.yaml -n "${FRAMEWORK}" -p $(go env GOPATH)/bin

      - uses: actions/upload-artifact@v5
        with:
          name: policy
          path: policy.yaml
          retention-days: 5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push bundle
        env:
          ORG: ${{ github.event.repository.owner.login }}
        run: cd ./policies/opa/ && oras push "ghcr.io/$ORG/opa-bundle:dev" ./policy
